"""Local development provider.

This exists so the pipeline, the queue, the UI and the tests can be exercised without
burning provider credits or requiring network access. It is **not** an assessment engine:

* It is refused at startup when `APP_ENV=production` (see `Settings.validate_for_environment`).
* Every result it returns carries `provider="mock"` through to the database and the UI, so a
  mock-derived record is always identifiable.
* It emits no prices and no market values at all. Fabricating those is the one thing this
  system must never do, and a fixture price is indistinguishable from a real one once it
  reaches an agent's screen. Market research against a mock simply reports `UNAVAILABLE`.

Output is derived deterministically from a hash of the input, so the same image always
produces the same finding and tests are reproducible.
"""

from __future__ import annotations

import hashlib
import json
import time
import uuid

from app.ai.base import AIProvider, CompletionResult, ImagePayload, VisionProvider
from app.core.enums import DamageSeverity, DamageType, RepairAction

_DAMAGE_FIXTURES = [
    ("FRONT_BUMPER", DamageType.CRACK, DamageSeverity.HIGH, RepairAction.REPLACE,
     "Continuous crack across the lower bumper with visible edge separation."),
    ("HEADLIGHT_LEFT", DamageType.BROKEN, DamageSeverity.MEDIUM, RepairAction.REPLACE,
     "Lens fractured; internal reflector visible through the break."),
    ("BONNET", DamageType.DENT, DamageSeverity.MEDIUM, RepairAction.REPAIR,
     "Shallow deformation near the leading edge without paint breakthrough."),
    ("DOOR_FRONT_LEFT", DamageType.SCRATCH, DamageSeverity.LOW, RepairAction.REPAIR,
     "Surface scratching along the door skin; clear coat affected only."),
    ("FENDER_RIGHT", DamageType.DEFORMATION, DamageSeverity.HIGH, RepairAction.REPLACE,
     "Panel pushed inward with a crease running to the wheel arch."),
]

_VEHICLE_FIXTURES = [
    ("Toyota", "Prius", 2018, "silver", "HATCHBACK"),
    ("Honda", "Civic", 2016, "white", "SEDAN"),
    ("Suzuki", "Swift", 2019, "red", "HATCHBACK"),
    ("Nissan", "X-Trail", 2015, "black", "SUV"),
]


def _seed(*parts: object) -> int:
    digest = hashlib.sha256("|".join(str(p) for p in parts).encode()).hexdigest()
    return int(digest[:8], 16)


class _MockBase:
    name = "mock"

    def is_configured(self) -> bool:
        return True

    @staticmethod
    def _result(payload: dict, model: str) -> CompletionResult:
        return CompletionResult(
            text=json.dumps(payload),
            provider="mock",
            model=model,
            request_id=uuid.uuid4().hex,
            latency_ms=int(time.perf_counter() * 0) + 12,
            input_tokens=0,
            output_tokens=0,
        )


class MockProvider(_MockBase, AIProvider):
    @property
    def text_model(self) -> str:
        return "mock-text"

    def complete(
        self, *, system: str, prompt: str, temperature: float = 0.1, max_tokens: int = 4096
    ) -> CompletionResult:
        seed = _seed(prompt)
        lowered = prompt.lower()

        if "customerinputextraction" in lowered or "possible_damage_parts" in lowered:
            mentioned = [
                code for code, *_ in _DAMAGE_FIXTURES
                if code.split("_")[0].lower() in lowered
            ]
            payload = {
                "possible_damage_parts": mentioned[:2],
                "possible_impact_area": "front-left" if "front" in lowered else None,
                "mentioned_location": None,
                "third_party_involved": "another vehicle" in lowered,
                "injuries_mentioned": "injur" in lowered,
                "confidence": 0.55,
                "notes": ["Generated by the mock provider; not a real extraction."],
            }
        elif "estimatereasoning" in lowered or "labour_hours_estimate" in lowered:
            items = []
            for code, damage_type, severity, action, _ in _DAMAGE_FIXTURES:
                if code.lower() in lowered:
                    items.append(
                        {
                            "canonical_part": code,
                            "action": action.value,
                            "action_rationale": (
                                f"{damage_type.value.lower()} at {severity.value} severity."
                            ),
                            "labour_hours_estimate": 2.0 + (seed % 3),
                            "paint_panels": 1.0 if action is RepairAction.REPAIR else 0.0,
                            "confidence": 0.6,
                        }
                    )
            payload = {"items": items, "notes": ["Mock provider output."]}
        elif "partnormalization" in lowered or "is_relevant" in lowered:
            payload = {
                "canonical_part": None,
                "is_relevant": False,
                "compatibility_confidence": 0.0,
                "notes": ["The mock provider does not normalise real listings."],
            }
        elif "marketinterpretation" in lowered:
            # No fabricated listings, ever.
            payload = {
                "listings": [],
                "notes": ["The mock provider does not produce market data."],
            }
        else:
            payload = {
                "summary": (
                    "Preliminary assessment generated by the local mock provider. "
                    "No real model analysed this claim."
                ),
                "key_findings": ["Mock provider active — findings are illustrative only."],
                "evidence_gaps": ["A configured AI provider is required for a real assessment."],
                "recommended_next_steps": ["Manual review by an authorised agent."],
                "confidence": 0.3,
            }

        return self._result(payload, self.text_model)


class MockVisionProvider(_MockBase, VisionProvider):
    @property
    def vision_model(self) -> str:
        return "mock-vision"

    def analyze(
        self,
        *,
        system: str,
        prompt: str,
        images: list[ImagePayload],
        temperature: float = 0.1,
        max_tokens: int = 4096,
    ) -> CompletionResult:
        image_bytes = images[0].data if images else b""
        seed = _seed(hashlib.sha256(image_bytes).hexdigest(), prompt[:80])
        lowered = prompt.lower()

        if "registration" in lowered or "plate" in lowered:
            payload = {
                "plate_visible": seed % 3 != 0,
                "registration_number": f"WP MOCK-{seed % 9000 + 1000}" if seed % 3 != 0 else None,
                "confidence": 0.42,
                "country_format_guess": None,
                "notes": ["Mock OCR; confirm the registration with the customer."],
            }
        elif "make" in lowered and "model" in lowered and "damage" not in lowered:
            make, model, year, color, body = _VEHICLE_FIXTURES[seed % len(_VEHICLE_FIXTURES)]
            payload = {
                "make": make,
                "model": model,
                "variant": None,
                "year_estimate": year,
                "year_range": [year - 1, year + 1],
                "color": color,
                "vehicle_type": body,
                "orientation": "FRONT_LEFT_QUARTER",
                "vehicle_visible": True,
                "multiple_vehicles": False,
                "confidence": 0.55,
                "notes": ["Mock identification; not derived from the image content."],
            }
        else:
            count = 1 + (seed % 2)
            damages = []
            for i in range(count):
                code, damage_type, severity, action, explanation = _DAMAGE_FIXTURES[
                    (seed + i) % len(_DAMAGE_FIXTURES)
                ]
                damages.append(
                    {
                        "canonical_part": code,
                        "damage_type": damage_type.value,
                        "severity": severity.value,
                        "confidence": 0.5 + (i * 0.05),
                        "bounding_box": {
                            "x": 0.15 + i * 0.2, "y": 0.35, "w": 0.28, "h": 0.22
                        },
                        "recommended_action": action.value,
                        "explanation": explanation,
                    }
                )
            payload = {
                "vehicle_visible": True,
                "multiple_vehicles": False,
                "quality_sufficient": True,
                "damages": damages,
                "notes": ["Mock detection; findings are illustrative and require review."],
            }

        return self._result(payload, self.vision_model)
