"""Assembles database rows into API read models.

This is the single place where economic values cross into responses, so it is the single
place that enforces the rule: a value is either `AVAILABLE` with a currency and sources, or
`UNAVAILABLE` with a reason and a manual-verification flag. Nothing downstream can render
a fabricated number because nothing downstream ever receives a bare figure.
"""

from __future__ import annotations

from decimal import Decimal

from sqlalchemy.orm import Session

from app.core.enums import ActorType, DataStatus
from app.core.parts import part_display_name
from app.models.assessment import DamageAssessment, DamagedPart
from app.models.claim import Claim
from app.models.estimate import RepairEstimate
from app.models.market import VehicleValuation
from app.models.user import User
from app.schemas.claim import (
    AnnotationResponse,
    AssessmentResponse,
    ClaimDetailResponse,
    ClaimImageResponse,
    ClaimNoteResponse,
    ClaimStatusResponse,
    ClaimSummaryResponse,
    DamagedPartResponse,
    EstimateLineResponse,
    EstimateResponse,
    FraudSignalResponse,
    ImageMetadataResponse,
    LocationResponse,
    MarketDataResponse,
    PartPriceResponse,
    PriceSourceResponse,
    ReconciliationResponse,
    TimelineEvent,
    ValuationSourceResponse,
    VehicleIdentificationResponse,
)
from app.schemas.common import MoneyRange
from app.services.images import ImageService

ESTIMATE_DISCLAIMER = (
    "This is a preliminary estimate generated by AI from the submitted photographs, the "
    "information you provided and publicly available market data. The final insurance "
    "assessment may differ following physical inspection and review by an authorised agent."
)

ASSESSMENT_DISCLAIMER = (
    "This assessment is AI-generated and preliminary. It is not an insurance decision and "
    "not a settlement offer. An authorised insurance agent reviews every claim before any "
    "decision is made."
)


def _float(value: Decimal | float | None) -> float | None:
    return float(value) if value is not None else None


class ClaimPresenter:
    def __init__(self, db: Session):
        self.db = db
        self.images = ImageService(db)

    # ── Images ──────────────────────────────────────────────

    def image(self, image) -> ClaimImageResponse:
        url, annotated_url = self.images.presign(image)
        return ClaimImageResponse(
            id=image.id,
            image_role=image.image_role,
            original_filename=image.original_filename,
            mime_type=image.mime_type,
            file_size=image.file_size,
            width=image.width,
            height=image.height,
            quality_score=image.quality_score,
            blur_score=image.blur_score,
            validation_status=image.validation_status,
            validation_errors=image.validation_errors or [],
            customer_note=image.customer_note,
            created_at=image.created_at,
            url=url,
            annotated_url=annotated_url,
            image_metadata=(
                ImageMetadataResponse.model_validate(image.image_metadata)
                if image.image_metadata
                else None
            ),
            annotations=[AnnotationResponse.model_validate(a) for a in image.annotations],
        )

    # ── Prices ──────────────────────────────────────────────

    def part_price(self, part: DamagedPart) -> MoneyRange:
        summary = part.price_summary
        if summary is None:
            return MoneyRange.unavailable(
                "Part pricing has not been researched for this component yet."
            )
        if summary.status is DataStatus.UNAVAILABLE or summary.price_min is None:
            return MoneyRange.unavailable(
                summary.unavailable_reason
                or "No reliable price was found from the permitted market sources."
            )
        return MoneyRange.available(
            summary.price_min,
            summary.price_max or summary.price_min,
            summary.currency,
            median=summary.price_median,
            confidence=_float(summary.price_confidence),
            source_count=summary.source_count,
        )

    def part_prices(self, claim: Claim) -> list[PartPriceResponse]:
        assessment = claim.latest_assessment
        if assessment is None:
            return []

        results: list[PartPriceResponse] = []
        for part in assessment.damaged_parts:
            summary = part.price_summary
            results.append(
                PartPriceResponse(
                    damaged_part_id=part.id,
                    canonical_part=part.canonical_part,
                    display_name=part.display_name,
                    price=self.part_price(part),
                    dominant_grade=summary.dominant_grade if summary else None,
                    confidence_reason=summary.confidence_reason if summary else None,
                    sources=[
                        PriceSourceResponse.model_validate(s)
                        for s in sorted(part.price_sources, key=lambda s: s.price)
                    ],
                )
            )
        return results

    # ── Damage and reconciliation ───────────────────────────

    def damaged_part(self, part: DamagedPart) -> DamagedPartResponse:
        return DamagedPartResponse(
            id=part.id,
            canonical_part=part.canonical_part,
            display_name=part.display_name,
            damage_type=part.damage_type,
            severity=part.severity,
            confidence=_float(part.confidence),
            bounding_box=part.bounding_box,
            recommended_action=part.recommended_action,
            action_rationale=part.action_rationale,
            explanation=part.explanation,
            customer_reported=part.customer_reported,
            ai_detected=part.ai_detected,
            agent_confirmed=part.agent_confirmed,
            agreement=part.agreement,
            image_id=part.image_id,
            price=self.part_price(part),
        )

    def reconciliation(self, assessment: DamageAssessment) -> ReconciliationResponse:
        """The customer-vs-AI diff, stated plainly rather than merged away."""
        parts = assessment.damaged_parts
        customer = sorted({p.display_name for p in parts if p.customer_reported})
        ai = sorted({p.display_name for p in parts if p.ai_detected})
        both = sorted({p.display_name for p in parts if p.customer_reported and p.ai_detected})
        ai_only = sorted({p.display_name for p in parts if p.ai_detected and not p.customer_reported})
        customer_only = sorted(
            {p.display_name for p in parts if p.customer_reported and not p.ai_detected}
        )

        fragments = [f"You reported {len(customer)} part(s); the AI detected {len(ai)}."]
        if both:
            fragments.append(f"Both agree on: {', '.join(both)}.")
        if ai_only:
            fragments.append(
                f"The AI additionally found possible damage to: {', '.join(ai_only)}."
            )
        if customer_only:
            fragments.append(
                f"You reported damage the AI could not confirm from the photographs: "
                f"{', '.join(customer_only)}."
            )
        if ai_only or customer_only:
            fragments.append("Manual verification is recommended.")

        return ReconciliationResponse(
            customer_reported=customer,
            ai_detected=ai,
            confirmed_by_both=both,
            ai_only=ai_only,
            customer_only=customer_only,
            summary=" ".join(fragments),
            manual_verification_recommended=bool(ai_only or customer_only),
        )

    def assessment(self, claim: Claim) -> AssessmentResponse | None:
        assessment = claim.latest_assessment
        if assessment is None:
            return None

        return AssessmentResponse(
            claim_id=claim.id,
            status=claim.status,
            generated_at=assessment.created_at,
            provider=assessment.provider,
            model=assessment.model,
            vehicle=VehicleIdentificationResponse(
                make=assessment.vehicle_make,
                model=assessment.vehicle_model,
                variant=assessment.vehicle_variant,
                year=assessment.vehicle_year,
                color=assessment.vehicle_color,
                vehicle_type=assessment.vehicle_type,
                confidence=_float(assessment.vehicle_confidence),
                registration_number=assessment.effective_registration,
                ocr_confidence=_float(assessment.ocr_confidence),
                registration_confirmed=assessment.registration_confirmed_by_customer,
                conflict_with_customer=assessment.vehicle_conflict,
                conflict_detail=assessment.vehicle_conflict_detail,
            ),
            damaged_parts=[self.damaged_part(p) for p in assessment.damaged_parts],
            reconciliation=self.reconciliation(assessment),
            summary_text=assessment.summary_text,
            stage_confidences={
                k: float(v) for k, v in (assessment.stage_confidences or {}).items()
                if isinstance(v, (int, float))
            },
            overall_confidence=_float(claim.overall_confidence),
            manual_review_required=claim.manual_review_required,
            manual_review_reasons=claim.manual_review_reasons or [],
            notes=assessment.notes or [],
            disclaimer=ASSESSMENT_DISCLAIMER,
        )

    # ── Money ───────────────────────────────────────────────

    def estimate(self, claim: Claim) -> EstimateResponse | None:
        estimate: RepairEstimate | None = claim.latest_estimate
        if estimate is None:
            return None

        total = MoneyRange.available(
            estimate.estimated_min,
            estimate.estimated_max,
            estimate.currency,
            confidence=_float(estimate.confidence),
        )
        if estimate.is_partial:
            total.reason = (
                f"{len(estimate.unpriced_parts)} damaged part(s) could not be priced from the "
                "permitted market sources, so this total is incomplete."
            )
            total.manual_verification_required = True

        return EstimateResponse(
            claim_id=claim.id,
            total=total,
            parts_subtotal_min=estimate.parts_subtotal_min,
            parts_subtotal_max=estimate.parts_subtotal_max,
            labour_min=estimate.labour_min,
            labour_max=estimate.labour_max,
            paint_min=estimate.paint_min,
            paint_max=estimate.paint_max,
            materials_min=estimate.materials_min,
            materials_max=estimate.materials_max,
            lines=[EstimateLineResponse.model_validate(line) for line in estimate.lines],
            is_partial=estimate.is_partial,
            unpriced_parts=[part_display_name(c) for c in (estimate.unpriced_parts or [])],
            damage_to_value_ratio=_float(estimate.damage_to_value_ratio),
            labour_rate_used=estimate.labour_rate_used,
            paint_rate_used=estimate.paint_rate_used,
            calculation_notes=estimate.calculation_notes,
            agent_adjusted_min=estimate.agent_adjusted_min,
            agent_adjusted_max=estimate.agent_adjusted_max,
            agent_adjustment_reason=estimate.agent_adjustment_reason,
            disclaimer=ESTIMATE_DISCLAIMER,
        )

    def market_data(self, claim: Claim) -> MarketDataResponse:
        valuation: VehicleValuation | None = claim.latest_valuation
        assessment = claim.latest_assessment

        if valuation is None:
            return MarketDataResponse(
                claim_id=claim.id,
                vehicle_label=assessment.vehicle_label if assessment else None,
                valuation=MoneyRange.unavailable("Market research has not run for this claim yet."),
            )

        if valuation.status is DataStatus.UNAVAILABLE or valuation.estimated_min is None:
            value = MoneyRange.unavailable(
                valuation.unavailable_reason
                or "No reliable market valuation was found for this vehicle."
            )
        else:
            value = MoneyRange.available(
                valuation.estimated_min,
                valuation.estimated_max or valuation.estimated_min,
                valuation.currency,
                median=valuation.median_value,
                confidence=_float(valuation.confidence),
                source_count=valuation.source_count,
            )

        label = " ".join(
            str(p) for p in (valuation.make, valuation.model, valuation.year) if p
        )
        return MarketDataResponse(
            claim_id=claim.id,
            vehicle_label=label or (assessment.vehicle_label if assessment else None),
            valuation=value,
            confidence_reason=valuation.confidence_reason,
            sources=[ValuationSourceResponse.model_validate(s) for s in valuation.sources],
        )

    def estimate_range(self, claim: Claim) -> MoneyRange | None:
        estimate = claim.latest_estimate
        if estimate is None:
            return None
        return MoneyRange.available(
            estimate.estimated_min,
            estimate.estimated_max,
            estimate.currency,
            confidence=_float(estimate.confidence),
        )

    # ── Timeline ────────────────────────────────────────────

    def timeline(self, claim: Claim) -> list[TimelineEvent]:
        events: list[TimelineEvent] = []

        for event in claim.status_events:
            actor_name = None
            if event.actor_user_id:
                actor = self.db.get(User, event.actor_user_id)
                actor_name = actor.full_name if actor else None
            events.append(
                TimelineEvent(
                    at=event.created_at,
                    kind="status",
                    actor_type=event.actor_type,
                    actor_name=actor_name,
                    title=event.to_status.value.replace("_", " ").title(),
                    detail=event.note,
                )
            )

        for note in claim.notes:
            if note.deleted_at:
                continue
            author = self.db.get(User, note.author_user_id) if note.author_user_id else None
            events.append(
                TimelineEvent(
                    at=note.created_at,
                    kind="note",
                    actor_type=ActorType.AGENT,
                    actor_name=author.full_name if author else None,
                    title="Note added",
                    detail=note.body,
                )
            )

        return sorted(events, key=lambda e: e.at)

    # ── Composite views ─────────────────────────────────────

    def summary(self, claim: Claim) -> ClaimSummaryResponse:
        assessment = claim.latest_assessment
        location = claim.location
        first_image = min(claim.images, key=lambda i: i.display_order, default=None)
        captures = [
            img.image_metadata.captured_at
            for img in claim.images
            if img.image_metadata and img.image_metadata.captured_at
        ]
        thumbnail = None
        if first_image is not None:
            thumbnail, _ = self.images.presign(first_image)
        return ClaimSummaryResponse(
            id=claim.id,
            claim_number=claim.claim_number,
            status=claim.status,
            priority=claim.priority,
            vehicle_label=(
                assessment.vehicle_label
                if assessment
                else (claim.vehicle.display_name if claim.vehicle else self._stated_label(claim))
            ),
            customer_name=(
                claim.customer.user.full_name if claim.customer and claim.customer.user else None
            ),
            image_count=len(claim.images),
            damaged_part_count=len(assessment.damaged_parts) if assessment else 0,
            estimate=self.estimate_range(claim),
            location_label=(location.city or location.address) if location else None,
            location_latitude=location.latitude if location else None,
            location_longitude=location.longitude if location else None,
            location_source=location.source if location else None,
            thumbnail_url=thumbnail,
            accident_datetime=claim.accident_datetime,
            photo_captured_at=min(captures) if captures else None,
            assigned_agent_name=(
                claim.assigned_agent.user.full_name
                if claim.assigned_agent and claim.assigned_agent.user
                else None
            ),
            manual_review_required=claim.manual_review_required,
            overall_confidence=_float(claim.overall_confidence),
            created_at=claim.created_at,
            submitted_at=claim.submitted_at,
        )

    def status(self, claim: Claim) -> ClaimStatusResponse:
        return ClaimStatusResponse(
            claim_id=claim.id,
            status=claim.status,
            pipeline_stage=claim.pipeline_stage,
            progress=claim.pipeline_progress or {},
            ai_completed_at=claim.ai_completed_at,
            manual_review_required=claim.manual_review_required,
        )

    def detail(self, claim: Claim, *, include_internal: bool) -> ClaimDetailResponse:
        report = claim.damage_report
        notes = [
            n for n in claim.notes
            if not n.deleted_at and (include_internal or n.visibility.value == "CUSTOMER_VISIBLE")
        ]

        return ClaimDetailResponse(
            id=claim.id,
            claim_number=claim.claim_number,
            status=claim.status,
            priority=claim.priority,
            created_at=claim.created_at,
            submitted_at=claim.submitted_at,
            ai_completed_at=claim.ai_completed_at,
            customer_name=(
                claim.customer.user.full_name if claim.customer and claim.customer.user else None
            ),
            customer_email=(
                claim.customer.user.email
                if include_internal and claim.customer and claim.customer.user
                else None
            ),
            customer_phone=(
                claim.customer.user.phone
                if include_internal and claim.customer and claim.customer.user
                else None
            ),
            policy_number=claim.policy.policy_number if claim.policy else None,
            vehicle={
                "make": claim.stated_make,
                "model": claim.stated_model,
                "variant": claim.stated_variant,
                "year": claim.stated_year,
                "color": claim.stated_color,
                "registration_number": claim.stated_registration,
            },
            accident_datetime=claim.accident_datetime,
            accident_description=claim.accident_description,
            customer_vehicle_description=claim.customer_vehicle_description,
            customer_reported_parts=[
                part_display_name(c) for c in (report.all_reported_part_codes if report else [])
            ],
            customer_free_text_parts=report.free_text_parts if report else None,
            images=[self.image(i) for i in sorted(claim.images, key=lambda i: i.display_order)],
            assessment=self.assessment(claim),
            estimate=self.estimate(claim),
            market_data=self.market_data(claim),
            part_prices=self.part_prices(claim),
            location=LocationResponse.model_validate(claim.location) if claim.location else None,
            fraud_signals=(
                [FraudSignalResponse.model_validate(s) for s in claim.fraud_signals]
                if include_internal
                else []
            ),
            notes=[
                ClaimNoteResponse(
                    id=n.id,
                    body=n.body,
                    visibility=n.visibility,
                    created_at=n.created_at,
                    author_name=(
                        self.db.get(User, n.author_user_id).full_name
                        if n.author_user_id and self.db.get(User, n.author_user_id)
                        else None
                    ),
                )
                for n in notes
            ],
            timeline=self.timeline(claim),
            manual_review_required=claim.manual_review_required,
            manual_review_reasons=claim.manual_review_reasons or [],
            pipeline_stage=claim.pipeline_stage,
            pipeline_progress=claim.pipeline_progress or {},
        )

    @staticmethod
    def _stated_label(claim: Claim) -> str | None:
        parts = [str(p) for p in (claim.stated_make, claim.stated_model, claim.stated_year) if p]
        return " ".join(parts) if parts else None
